### ISSUE TITLE
Send hyphenated string

### ISSUE THREAD

**Issue by venzen** [jghauser/kitty-runner.nvim#7]
My use of kitty-runner is unconventional in that I'm using the plugin as a text inspector. I work with markdown documents that contain a mix of English and Thai script. Thai script is rendered much smaller than English script, so I sometimes send text from Nvim to Kitty (with a large fontsize) to magnify the Thai script and make it readable.

Howver, some lines that are sent via `:KittySendLines` do not get rendered by Kitty. An example is this line from an unordered markdown list:

```
- enthusiastic = `กระตือรือร้น`
```
If the first line that is sent starts with a hyphen, then Kitty does not show it or subsequent lines. However, if a hyphenated line follows a line without a hyphen (it could be a blank line), then all lines are rendered as expected. I have not encountered other anomalies yet.

Presumably, kitty-runner is interpreting the hyphen to mean `stdin` and negating it? Or maybe there is another reason why the string gets gobbled.

It would be useful if there was a `:KittySendRawStr` function that would allow arbitrary text to be passed to Kitty. Perhaps it would be possible for this function to also send only text selected via Visual mode?

**Comment by jghauser** [comment]
Hi!

Odd, lines that start with '-' really aren't sent at all. This clearly is a bug. There's no reason why such lines shouldn't be sent even in the normal case. I don't think a special command is required for this at all. I'll try to fix this as soon as possible.

The second issue, re sending the visual selection, is something that I've wanted to implement since the very beginning. I think I didn't do it then because `vim.region` wasn't merged yet. As it is merged now, I'll give this a shot. When I get to it, it should be used with the standard `KittySendLines` command whenever it is called during a visual selection. I might take a bit longer to implement this (but I think fixing the first bug should get most of your use case to work).

Does that seem reasonable to you?

**Comment by venzen** [comment]
Thank you for your reply and dedication @jghauser. This is a reasonable plan of action indeed.

**Comment by jghauser** [comment]
Sending strings starting with '-' should now work. Let me know if something doesn't work as expected.

**Comment by venzen** [comment]
Thank you for the fix, @jghauser. I've tried commit c41158a in Nvim and a single hyphenated string is now being sent as expected.  I notice that the required change was to add "--" to the `run_cmd`:

```
run_cmd = { "send-text", "--" },
```

Interesting. Is "--" a prefix expected by kitty?

**Comment by jghauser** [comment]
Great to hear! I actually got the solution from the creator of kitty. The double dash is used by kitty (and many other programs) to signify the end of the command line options, and that's exactly what we needed.

EDIT: The original problem was that strings starting with '-' were interpreted by kitty as specifying a new option rather than the string to be sent with `send-text`.

**Comment by jghauser** [comment]
I'm closing this issue. I've created another issue to track the feature request regarding sending the visually selected text.

**Comment by jghauser** [comment]
Hi!

Odd, lines that start with '-' really aren't sent at all. This clearly is a bug. There's no reason why such lines shouldn't be sent even in the normal case. I don't think a special command is required for this at all. I'll try to fix this as soon as possible.

The second issue, re sending the visual selection, is something that I've wanted to implement since the very beginning. I think I didn't do it then because `vim.region` wasn't merged yet. As it is merged now, I'll give this a shot. When I get to it, it should be used with the standard `KittySendLines` command whenever it is called during a visual selection. I might take a bit longer to implement this (but I think fixing the first bug should get most of your use case to work).

Does that sound reasonable to you?
